<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Trainee;
use App\Models\EmploymentLog;
use App\Models\Cohort;


class Academy extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'slug',
        'location',
        'description',
        'academy_img',
        
    ];
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function trainees()
    {
        return $this->hasMany(Trainee::class);
    }

    public function employmentLogs()
    {
        return $this->hasMany(EmploymentLog::class);
    }

    public function cohorts()
    {
        return $this->hasMany(Cohort::class);
    }


}
