<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cohort extends Model
{
    use HasFactory;

    protected $fillable = [
        'number',
        'name',
        'start_date', 'end_date', 'training_location', 'description','fund_id',
        'academy_id', 'training_type', 'technology', 'donor_type', 'cohort_Rate','slug','cohort_status'
    ];

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function academy()
    {
        return $this->belongsTo(Academy::class);
    }

    // public function TrainingInfo()
    // {
    //     return $this->hasOne(TrainingInfo::class);
    // }


    public function trainees()
    {
        return $this->hasMany(Trainee::class);
    }

    public function employmentLogs()
    {
        return $this->hasMany(EmploymentLog::class);
    }

    public function fund()
    {
        return $this->hasOne(Fund::class);
    }
}
